spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MrLiCTO/app-cloud/
          search-paths: config/src/main/resources/config
        #native:
          #search-locations: classpath:/config
server:
  port: 8888
#eureka:
 # host: localhost
  #port: 8761