server:
  port: 8882
spring:
  rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
  redis:
    database: 0
    port: 6379
    pool:
      min-idle: 0
      max-idle: 8
      max-active: 8
    host: localhost
endpoints:
  restart:
    enabled: true
