spring:
  thymeleaf:
    cache: false
    check-template-location: true
    enabled: true
    encoding: utf-8
    mode: HTML5
    content-type: text/html
    prefix: classpath:/templates/
    suffix: .html
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 80
#logging:
  #pattern:
    #level: info
